project:
  type: website
  output-dir: docs

date-format: iso
execute:
  freeze: auto

repo-url: https://github.com/mvuorre/mvuorre.github.io

website:
  title: "Matti's homepage"
  site-url: https://vuorre.com
  description: Homepage of Matti Vuorre
  repo-url: https://github.com/mvuorre/mvuorre.github.io
  comments:
    giscus:
      repo: mvuorre/mvuorre.github.io
      repo-id: R_kgDOHk4rRg
      category: giscus
      category-id: DIC_kwDOHk4rRs4CQAdF
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme: light
  search:
    location: navbar
    type: overlay
  twitter-card: true
  open-graph: true
  page-navigation: true
  navbar:
    pinned: true
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: About
        href: personal.qmd
      - icon: rss
        href: index.xml

format:
  html:
    theme: 
      - zephyr
      - custom.scss
    mainfont: "Atkinson Hyperlegible"
    monofont: "Fira code"
    header-includes:
      - <script data-goatcounter="https://vuorre.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

