project:
  type: website
  output-dir: docs
  preview:
    port: 4321
  resources:
    - CNAME
repo-url: https://github.com/mvuorre/mvuorre.github.io
date-format: iso
execute:
  freeze: auto
website:
  title: "Matti's website"
  site-url: https://vuorre.com
  description: Matti's website
  repo-url: https://github.com/mvuorre/mvuorre.github.io
  draft-mode: unlinked
  favicon: images/icon/favicon-32x32.png
  comments:
    giscus:
      repo: mvuorre/mvuorre.github.io
      repo-id: R_kgDOHk4rRg
      category: giscus
      category-id: DIC_kwDOHk4rRs4CQAdF
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme: light
  search:
    location: navbar
    type: overlay
  twitter-card: true
  open-graph: true
  page-navigation: true
  navbar:
    pinned: true
    left:
      - text: Works
        href: publications.qmd
      - text: Blog
        href: blog.qmd
      - text: RSS
        href: blog.xml
format:
  html:
    theme: [zephyr, light.scss]
    mainfont: system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif
    monofont: ui-monospace, "SF Mono", Consolas, monospace
    highlight-style: a11y
    header-includes:
      - <script data-goatcounter="https://vuorre.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
