project:
  type: website
  output-dir: docs

date-format: iso
execute:
  freeze: auto

website:
  title: "Matti's homepage"
  site-url: https://vuorre.netlify.app
  description: Homepage of Matti Vuorre
  repo-url: https://github.com/mvuorre/mvuorre.github.io
  comments:
    giscus:
      repo: mvuorre/mvuorre.github.io
      repo-id: R_kgDOHk4rRg
      category: giscus
      category-id: DIC_kwDOHk4rRs4CQAdF
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme: light
  search:
    location: navbar
    type: overlay
  twitter-card: true
  open-graph: true
  page-navigation: true
  navbar:
    pinned: true
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - personal.qmd
      - text: Links
        menu:
          - text: RSS
            href: blog.xml
          - text: Email
            href: "mailto:m.j.vuorre@tilburguniversity.edu"
          - text: ORCID
            href: "https://orcid.org/0000-0001-5052-066X"
          - text: Mastodon
            href: "https://bayes.club/@matti"
          - text: GitHub
            href: "https://github.com/mvuorre"
          - text: "CV"
            href: "https://github.com/mvuorre/CV/raw/main/vuorre-matti.pdf"
          - text: Twitter
            href: "https://twitter.com/vuorre"
          - text: LinkedIn
            href: "https://www.linkedin.com/in/matti-vuorre"
          - text: Buy me a coffee
            href: https://www.buymeacoffee.com/vuorre

format:
  html:
    theme: 
      - zephyr
      - custom.scss
    mainfont: "Fira sans"
    monofont: "Fira code"
    header-includes:
      - <script data-goatcounter="https://vuorre.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

