project:
  type: website
  output-dir: docs
  resources:
    - CNAME
repo-url: https://github.com/mvuorre/mvuorre.github.io
date-format: iso
execute:
  freeze: auto
website:
  title: "Matti's website"
  site-url: https://vuorre.com
  description: Matti's website
  repo-url: https://github.com/mvuorre/mvuorre.github.io
  repo-actions: [edit, source, issue]
  draft-mode: unlinked
  comments:
    giscus:
      repo: mvuorre/mvuorre.github.io
      repo-id: R_kgDOHk4rRg
      category: giscus
      category-id: DIC_kwDOHk4rRs4CQAdF
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme: light
  search:
    location: navbar
    type: overlay
  twitter-card: true
  open-graph: true
  page-navigation: true
  navbar:
    pinned: true
    right:
      - text: Works
        href: publications.qmd
      - text: Blog
        href: blog.qmd
      - text: Now
        href: now.qmd
      - icon: rss
        href: blog.xml
      - icon: github
        href: "{{<meta repo-url >}}"
format:
  html:
    theme:
      light: [zephyr, _common.scss, custom.scss]
      dark: [darkly, _common.scss, custom-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    highlight-style: atom-one
    header-includes:
      - <script data-goatcounter="https://vuorre.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
