project:
  type: website
  output-dir: docs
  preview:
    port: 4321
  resources:
    - CNAME
repo-url: https://github.com/mvuorre/mvuorre.github.io
date-format: iso
execute:
  freeze: auto
website:
  title: "Matti's website"
  site-url: https://vuorre.com
  description: Matti's website
  repo-url: https://github.com/mvuorre/mvuorre.github.io
  repo-actions: [edit, source, issue]
  draft-mode: unlinked
  favicon: images/icon/favicon-32x32.png
  comments:
    giscus:
      repo: mvuorre/mvuorre.github.io
      repo-id: R_kgDOHk4rRg
      category: giscus
      category-id: DIC_kwDOHk4rRs4CQAdF
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme: light
  search:
    location: navbar
    type: overlay
  twitter-card: true
  open-graph: true
  page-navigation: true
  navbar:
    pinned: true
    right:
      - text: Works
        href: publications.qmd
      - text: Blog
        href: blog.qmd
      - icon: rss
        href: blog.xml
      - icon: github
        href: "{{<meta repo-url >}}"
      - icon: bluesky
        href: https://bsky.app/profile/matti.vuorre.com
format:
  html:
    theme:
      light: [zephyr, light.scss]
      dark: [darkly, dark.scss]
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y
    header-includes:
      - <script data-goatcounter="https://vuorre.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
