---
title: "Matti Vuorre"
subtitle: |
  Psychological scientist
title-block-banner: false
comments: false
---

I am a researcher at Tilburg University, where I study psychological functioning in the context of digital technologies and online/virtual environments. Much of my most recent research has focused on the roles that digital technologies---particularly video games---play in individuals' well-being. In my work, I apply statistical methods to large-scale datasets and conduct controlled experiments. I also place great emphasis on the transparency and reproduciblity of all my work. For more details, you can take a look at my [vita](https://github.com/mvuorre/CV/raw/main/vuorre-matti.pdf). You can also check out my Tilburg profile [here](https://www.tilburguniversity.edu/staff/m-j-vuorre/).

In addition to my current research topics, I have written about [meta-cognition](https://link.springer.com/article/10.1007%2Fs11409-020-09257-1) and have a keen interest in methodology (e.g. [here](https://journals.sagepub.com/doi/10.1177/2515245918754826)) and applied statistics ([here](https://www.tandfonline.com/doi/full/10.1080/21642850.2018.1428102)) within the psychological sciences. I run a very sporadic [blog](blog.html) about statistics, psychology, science and the wonderful R statistical programming environment, and [another blog](https://matti.bearblog.dev/) for rants that probably shouldn't be online.

## Selected writings

Here are some recent works that I was particularly happy to have contributed to. (Unlike children, you *can* have favorite papers.)

- "*An intensive longitudinal dataset of in-game player behaviour and well-being in PowerWash Simulator*" ([web](https://www.nature.com/articles/s41597-023-02530-3) \| [pdf](https://www.nature.com/articles/s41597-023-02530-3.pdf) \| [code & data](https://doi.org/10.17605/OSF.IO/WPEH6))
- "*There Is No Evidence That Associations Between Adolescents' Digital Technology Engagement and Mental Health Problems Have Increased.*" ([web](https://doi.org/10.1177/2167702621994549) \| [pdf](https://journals.sagepub.com/doi/pdf/10.1177/2167702621994549) \| [code](https://github.com/digital-wellbeing/timetrends))
- "*Time spent playing video games is unlikely to impact well-being.*" ([web](https://royalsocietypublishing.org/doi/full/10.1098/rsos.220411) \| [pdf](https://royalsocietypublishing.org/doi/pdf/10.1098/rsos.220411?download=true) \| [code & data](https://zenodo.org/badge/latestdoi/373533911))
- "*Ordinal Regression Models in Psychology: A Tutorial.*" ([web](https://doi.org/10.1177/2515245918823199) \| [pdf](https://journals.sagepub.com/doi/pdf/10.1177/2515245918823199) \| [code & data](https://osf.io/cu8jv/))

I believe scientific communication should be available to all, so all these papers are openly available. If you find a paper of mine that you'd be interested in reading, and which somehow isn't available online, let me know and I'll fix it ASAP. In the future, we'll figure out a way to get rid of publishers entirely.

## Bibliography

You can find all my publications on [ORCID](https://orcid.org/0000-0001-5052-066X), [Zotero](https://www.zotero.org/vuorre), or [Google Scholar](https://scholar.google.com/citations?hl=en&user=I4DSy-8AAAAJ&view_op=list_works&sortby=pubdate). To make it easier for you to cite my work, [here](/matti-vuorre.bib) is a .bib file with references to all the works that I have contributed to.

## My links

[My website](https://vuorre.com) | [Bearblog](https://matti.bearblog.dev/) | [GitHub](https://github.com/mvuorre) | [ORCID](https://orcid.org/0000-0001-5052-066X) | [PREreview](https://prereview.org/profiles/0000-0001-5052-066X) | [Mastodon](https://bayes.club/@matti) | [CV](https://github.com/mvuorre/CV/raw/main/vuorre-matti.pdf) | [LinkedIn](https://www.linkedin.com/in/matti-vuorre) | [BlueSky](https://bsky.app/profile/matti.vuorre.com) | [email](mailto:m.j.vuorre@tilburguniversity.edu)

::: grid
::: {.g-col-6}
## Employment
- Tilburg University (2023 - )\
  *Assistant Professor*
- University of Oxford (2020 - 2022)\
  *Postdoctoral researcher*
- Columbia University (2018 - 2020)\
  *Postdoctoral Scientist*
:::
::: {.g-col-6}
## Education
- PhD (2018)\
  *Columbia University*
- MA (2015) & MSc (2017)\
  *Columbia University*
- BSc (Hons) in Psychology (2013)\
  *Victoria University of Wellington*
:::
:::

## Integrity statement

Academic research is a service conducted in the public interest without biases or hidden agendas. I aim to do so and conduct my work in accordance with [The European Code of Conduct for Research Integrity](https://allea.org/code-of-conduct/) and its four main principles: Reliability, Honesty, Respect, and Accountability.

I list all the sources of my research funding in [my CV](https://github.com/mvuorre/CV/raw/main/vuorre-matti.pdf), and all my external (to academic institutions) positions on my Tilburg University [profile page](https://research.tilburguniversity.edu/en/persons/matti-vuorre). My work is or has been funded in the past by Tilburg University, the Economic and Social Research Council, and the University of Oxford's John Fell Fund. I have provided in-kind consultations and served as a non-paid panel member for [Meta](https://about.meta.com/) and [K-Games](http://www.kgames.or.kr/introduction/greetings-eng/).

## Blogroll

[Statistical Modeling, Causal Inference, and Social Science](https://statmodeling.stat.columbia.edu/) | [The 100% CI](https://www.the100.ci/) | [Dorothy Bishop](https://deevybee.blogspot.com/) | [Andrew Heiss](https://www.andrewheiss.com/blog/) | [A. Solomon Kurz](https://solomonkurz.netlify.app/blog/) | [Ruben C. Arslan](https://rubenarslan.github.io/) | [Computational Psychology](http://haines-lab.com/#posts) | [Tobias Dienlin](https://tobiasdienlin.com/blog/) | [Making it as an early career academic](https://gavinbuckingham.wordpress.com/) | [Jan Vanhove](https://janhove.github.io/) | [Nick Ballou](https://nickballou.com/blog/) | [Steve Haroz](http://steveharoz.com/blog/) | [Lorne Campbell](https://www.lornecampbell.org/) | [Tidyverse](https://www.tidyverse.org/blog/) | [*[Suggest a link](https://github.com/mvuorre/mvuorre.github.io/issues)*]
