---
title: What I've been up to
toc: true
toc-depth: 2
toc-location: left
listing:
  - id: listing
    template: reading/custom.ejs
    contents:
      - reading/items.yml
    include:
      type: "*"
    sort: "date_read desc"
    page-size: 5
    date-format: "YYYY-MM-DD"
comments: false
---

<!-- Somehow these are required to make icons work in the EJS template. -->
<!-- {{< fa brands github >}} -->

## What I've been reading

This is a short selection of things I've been reading, watching, or listening to.

::: {#listing}
:::

```{r}
#| include: false

library(jsonlite)
library(fs)
library(tidyverse)
library(httr2)
knitr::opts_chunk$set(
  include = FALSE
)

# Query data from Zotero API and save JSON into a tibble
# Read Zotero API key from .Renviron
# todo better caching
path <- "reading/readings.csv"
if (!file.exists(path)) {
  readRenviron(".env")
  ZOTERO_API_KEY <- Sys.getenv(
    "ZOTERO_API_KEY",
    unset = errorCondition("No ZOTERO_API_KEY in .env")
  )

  req <- request("https://api.zotero.org/users/2244382/collections/4C5A7RQL/items") |>
    req_headers("Zotero-API-Key" = ZOTERO_API_KEY)

  resp <- req |>
    req_perform()

  body <- resp |>
    resp_body_string() |>
    fromJSON()

  items <- tibble(body$data)

  dat <- items |>
    filter(!(itemType %in% c("attachment"))) |>
    # Crazy hack to harmonize different author table formats
    mutate(
      creators = map(
        creators,
        ~ if ("name" %in% names(.x)) {
          mutate(
            .x,
            lastName = str_split_1(name, " ")[2],
            firstName = str_split_1(name, " ")[1],
            name = str_c(firstName, lastName, sep = " ")
          )
        } else {
          mutate(
            .x,
            name = str_c(firstName, lastName, sep = " ")
          )
        }
      )
    ) |>
    mutate(
      type = itemType,
      title = title,
      abstract = abstractNote,
      date, dateAdded, dateModified, accessDate,
      url,
      authors = map_chr(
        creators,
        ~ knitr::combine_words(.x$name, and = " & ")
      ),
      extra,
      .keep = "none"
    )
  write_csv(dat, path)
} else {
  dat <- read_csv(path)
}
```

```{r}
#| eval: true

path <- "reading/items.yml"

dat |>
  mutate(extra = ifelse(is.na(extra), "extra: ~", extra)) |>
  str_glue_data("
- title: >-
    {title}
  url: {url}
  date: {date}
  date_read: {dateModified}
  type: {type}
  authors: |
    {authors}
  abstract: |
    {str_remove_all(abstract, '\\n')}
  {str_replace(extra, '\\n', '\\n  ')}
") |>
  cat(file = path, sep = "\n")
```
