---
title: My publications
toc: true
toc-location: left
listing:
  - id: journal-articles
    template: publications/custom.ejs
    contents:
      - publications/items.yml
    include:
      type: "*"
    categories: true
    sort: "date desc"
    filter-ui: true
    page-size: 100
    date-format: "YYYY"
comments: false
---

<!-- Somehow these are required to make icons work in the EJS template. -->
<!-- {{< fa brands github >}} -->
<!-- {{< ai google-scholar >}} -->

You can find all my publications on this page, or on [ORCID](https://orcid.org/0000-0001-5052-066X), [Zotero](https://www.zotero.org/vuorre), or [Google Scholar](https://scholar.google.com/citations?hl=en&user=I4DSy-8AAAAJ&view_op=list_works&sortby=pubdate). You can also find preprints of most of my work on [PsyArXiv](https://osf.io/preprints/psyarxiv/discover?activeFilters=%5B%7B%22propertyVisibleLabel%22%3A%22Creator%22%2C%22propertyPathKey%22%3A%22creator%22%2C%22label%22%3A%22Matti%20Vuorre%22%2C%22value%22%3A%22https%3A%2F%2Fosf.io%2Ftdyix%22%7D%5D&sort=-dateCreated).

::: {#journal-articles}
:::

```{r}
#| include: false

library(jsonlite)
library(janitor)
library(fs)
library(tidyverse)
knitr::opts_chunk$set(
  include = FALSE
)

path <- "bibliography/bibliography.json"

# Wrangle data
dat <- fromJSON(path)$items |>
  tibble() |>
  clean_names() |>
  filter(item_type %in% c("journalArticle", "preprint")) |>
  mutate(
    publication = ifelse(
      item_type == "preprint",
      library_catalog,
      publication_title
    ),
    authors = map_chr(
      creators,
      ~ knitr::combine_words(.x$lastName, and = " & ")
    ),
    tags = map_chr(
      tags,
      ~ knitr::combine_words(.x$tag, and = "") |>
        str_to_lower()
    ),
    file = map_chr(
      attachments,
      ~ paste0("bibliography/", filter(.x, !is.na(.x$path))$path)
    )
  ) |>
  select(
    title,
    type = item_type,
    abstract = abstract_note,
    date,
    date_added,
    date_modified,
    publication,
    url, doi,
    authors,
    tags,
    file,
    rights,
    extra
  )

# Blacklisted DOIs that could lead to legal troubles
bad_dois <- c(
  "10.1016/S2352-4642(24)00332-8"
)
dat <- dat |>
  mutate(
    file = if_else(doi %in% bad_dois, NA, file)
  )
```

```{r}
#| eval: true

path <- "publications/items.yml"

# Note the Zotero 'Extra' field must contain items like
# license: CC-BY
# data: <URL>

dat |>
  mutate(extra = ifelse(is.na(extra), "extra: ~", extra)) |>
  str_glue_data("
- title: >-
    {title}
  url: {url}
  date: {date}
  type: {type}
  authors: |
    {authors}
  doi: {doi}
  outlet: >-
    {publication}
  file: {file}
  categories: [{tags}]
  abstract: |
    {str_remove_all(abstract, '\\n')}
  {str_replace(extra, '\\n', '\\n  ')}
") |>
  cat(file = path, sep = "\n")
```
